apiVersion: apps/v1
kind: Deployment
metadata:
  name: recive-hello2
  namespace: recivers
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recive-hello2
  template:
    metadata:
      labels:
        app: recive-hello2
    spec:
      containers:
        - name: recive
          image: wbe7/recive-rabbit:v0.6
          env:
            - name: QUEUE
              value: hello2
            - name: LOGIN
              value: wbe7
            - name: PASSWORD
              value: mindbox123
            - name: BROKER
              value: 34.89.173.76:5672